[package]
edition = "2018"
name = "wasm"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["swc_v1"]
swc_v1 = []

plugin = ["getrandom/js", "turbopack-binding/__swc_core_binding_wasm_plugin"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.66"
console_error_panic_hook = "0.1.6"
next-custom-transforms = { workspace = true }
once_cell = { workspace = true }
parking_lot_core = "=0.8.0"
path-clean = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = { version = "0.1.37" }
wasm-bindgen = { version = "0.2", features = ["enable-interning"] }
wasm-bindgen-futures = "0.4.8"
getrandom = { version = "0.2.9", default-features = false, features = ["js"] }
js-sys = "0.3.59"
serde-wasm-bindgen = "0.4.3"
turbopack-binding = { workspace = true, features = [
  "__swc_core_binding_wasm",
  "__feature_mdx_rs",
] }
swc_core = { workspace = true, features = ["ecma_ast_serde", "common"] }


# Workaround a bug
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# Workaround a bug
[package.metadata.wasm-pack.profile.dev]
wasm-opt = false
