[package]
name = "node-file-trace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node-file-trace"
path = "src/main.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
persistent_cache = ["dep:turbo-tasks-rocksdb"]
tokio_console = ["dep:console-subscriber", "tokio/tracing", "turbo-tasks/tokio_tracing"]

[dependencies]
clap = { version = "3.1.3", features = ["derive"] }
turbo-tasks = { path = "../turbo-tasks" }
# turbo-tasks-memory = { path = "../turbo-tasks-memory", features = ["log_running_tasks", "log_scheduled_tasks", "log_activate_tasks", "log_connect_tasks"] }
turbo-tasks-memory = { path = "../turbo-tasks-memory" }
turbo-tasks-rocksdb = { path = "../turbo-tasks-rocksdb", optional = true }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack = { path = "../turbopack" }
turbopack-core = { path = "../turbopack-core" }
anyhow = "1.0.47"
tokio = { version = "1.11.0", features = ["full"] }
json = "0.12.4"
serde = "1.0.136"
console-subscriber = { version = "0.1.6", optional = true }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
