[package]
name = "turbopack-dev-server"
version = "0.1.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
anyhow = "1.0.47"
"turbo-tasks" = { path = "../turbo-tasks" }
"turbo-tasks-fs" = { path = "../turbo-tasks-fs" }
"turbopack-core" = { path = "../turbopack-core" }
tokio = "1.11.0"
hyper = { version = "0.14", features = ["full"] }
serde = "1.0.136"
mime_guess = "2.0.4"

[build-dependencies]
"turbo-tasks-build" = { path = "../turbo-tasks-build" }
