[package]
name = "turbopack-convert-trace"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[[bin]]
name = "turbopack-convert-trace"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive", "env"] }
futures = { workspace = true }
indexmap = { workspace = true }
intervaltree = "0.2.7"
itertools = { workspace = true }
owo-colors = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
turbopack-cli-utils = { workspace = true }
