[package]
name = "turbopack-cli-utils"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.47"
clap = { version = "4.0.18", features = ["derive"] }
crossterm = "0.25"
owo-colors = "3"
serde = { version = "1.0.136", features = ["derive"] }
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbopack-core = { path = "../turbopack-core" }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
