[package]
name = "turbopack-static"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"

turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbo-tasks-hash = { path = "../turbo-tasks-hash" }
turbopack-core = { path = "../turbopack-core" }
turbopack-css = { path = "../turbopack-css" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }

md4 = "0.10.1"
serde = "1.0.136"

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
