[package]
name = "turbo-tasks-fs"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "mod"
harness = false

[features]
# Enables dynamic linking (and hot reloading) of embedded files/dirs.
# A binary built with this option **is not portable**, the directory
# path will be embedded into the binary.
dynamic_embed_contents = []
# Write a hashed version of each file to allow to debug conflicting writes
write_version = []

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
auto-hash-map = { workspace = true }
bitflags = "1.3.2"
bytes = { workspace = true }
concurrent-queue = { workspace = true }
dashmap = { workspace = true }
dunce = { workspace = true }
futures = { workspace = true }
futures-retry = { workspace = true }
include_dir = { version = "0.7.2", features = ["nightly"] }
indexmap = { workspace = true }
jsonc-parser = { version = "0.21.0", features = ["serde"] }
mime = { workspace = true }
notify = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-hash = { workspace = true }
unicode-segmentation = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
rstest = { workspace = true }
sha2 = "0.10.2"
tempfile = { workspace = true }
turbo-tasks-memory = { workspace = true }
turbo-tasks-testing = { workspace = true }

[build-dependencies]
turbo-tasks-build = { workspace = true }
