[package]
name = "next-page-static-info"
version = "0.1.0"
description = "SWC visitor to read page's static build information"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
swc_core = { workspace = true, features = [
  "ecma_ast",
  "common",
  "ecma_codegen",
  "ecma_parser",
  "ecma_quote",
  "ecma_visit",
  "ecma_visit_path",
  "ecma_utils",
  "testing",
  "base",
] }

[dev-dependencies]
swc_core = { workspace = true, features = ["testing_transform"] }
testing = { workspace = true }
