[package]
name = "turbopack-create-test-app"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

# don't publish this crate (for now)
publish = false

[[bin]]
name = "turbopack-create-test-app"
path = "src/main.rs"
bench = false

[lib]
bench = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
indoc = { workspace = true }
pathdiff = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
