[package]
name = "next-dev-tests"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

# don't publish this crate
publish = false

[features]
tokio_console = [
  "dep:console-subscriber",
  "tokio/tracing",
  "turbo-binding/__turbo_tasks_tokio_tracing",
]

[dependencies]
console-subscriber = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
chromiumoxide = { workspace = true, features = [
  "tokio-runtime",
], default-features = false }
dunce = { workspace = true }
futures = { workspace = true }
httpmock = { workspace = true, default-features = false, features = ["standalone"] }
lazy_static = { workspace = true }
mime = { workspace = true }
next-core = { workspace = true }
next-dev = { path = "../next-dev" }
owo-colors = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
testing = { workspace = true }
tokio = { workspace = true, features = ["full"] }
# For matching on errors from chromiumoxide. Keep in
# sync with chromiumoxide's tungstenite requirement.
tungstenite = { workspace = true }
turbo-binding = { workspace = true, features = [
  "__turbo_tasks_malloc",
  "__turbo_tasks_memory",
  "__turbo_tasks",
  "__turbo_tasks_fs",
  "__turbo_tasks_testing",
  "__turbopack_cli_utils",
  "__turbopack_test_utils",
  "__turbopack_core",
  "__turbopack_core_issue_path",
  "__turbopack_node",
  "__turbopack_dev_server",
  "__swc_transform_relay"
]}
turbo-tasks = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }

[build-dependencies]
turbo-binding = { workspace = true, features = [
  "__turbo_tasks_build"
]}
