[package]
name = "turbopack-css"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[dependencies]
anyhow = "1.0.47"
async-trait = "0.1.56"
indexmap = { workspace = true }
serde = "1.0.136"

turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbo-tasks-hash = { path = "../turbo-tasks-hash" }
turbopack-core = { path = "../turbopack-core" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-swc-utils = { path = "../turbopack-swc-utils" }

swc_core = { workspace = true, features = [
  "ecma_ast",
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_utils",
  "css_visit",
  "css_visit_path",
  "css_compat",
  "css_modules",
  "common",
  "common_concurrent",
] }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }
