[package]
name = "turbopack-tests"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

# don't publish this crate
publish = false

[dependencies]
turbopack = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
next-core = { workspace = true, features = ['native-tls'] }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
test-generator = { workspace = true }
tokio = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-env = { workspace = true }
turbo-tasks-fs = { workspace = true }
turbo-tasks-memory = { workspace = true }
turbopack-core = { workspace = true }
turbopack-env = { workspace = true }
turbopack-test-utils = { workspace = true }

[build-dependencies]
turbo-tasks-build = { workspace = true }

[features]
default = ["native-tls"]
native-tls = ["next-core/native-tls"]
rustls-tls = ["next-core/rustls-tls"]
