[package]
name = "next-core"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
base64 = "0.21.0"
lazy-regex = "3.0.1"
next-custom-transforms = { workspace = true }
once_cell = { workspace = true }
qstring = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
mime_guess = "2.0.4"
indoc = { workspace = true }
allsorts = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rustc-hash = { workspace = true }
turbopack-binding = { workspace = true, features = [
  "__swc_transform_modularize_imports",
  "__swc_transform_relay",
  "__swc_core_next_core",
  "__feature_auto_hash_map",
  "__turbo_tasks",
  "__turbo_tasks_bytes",
  "__turbo_tasks_env",
  "__turbo_tasks_fetch",
  "__turbo_tasks_fs",
  "__turbo_tasks_hash",
  "__turbopack",
  "__turbopack_build",
  "__turbopack_core",
  "__turbopack_dev",
  "__turbopack_ecmascript",
  "__turbopack_ecmascript_plugin",
  "__turbopack_ecmascript_runtime",
  "__turbopack_env",
  "__turbopack_static",
  "__turbopack_image",
  "__turbopack_node",
  "__turbopack_trace_utils",
] }

turbo-tasks = { workspace = true }
turbo-tasks-fs = { workspace = true }

[build-dependencies]
turbopack-binding = { workspace = true, features = ["__turbo_tasks_build"] }

[features]
next-font-local = []
native-tls = ["turbopack-binding/__turbo_tasks_fetch_native-tls"]
rustls-tls = ["turbopack-binding/__turbo_tasks_fetch_rustls-tls"]
plugin = ["turbopack-binding/__swc_core_binding_napi_plugin"]
image-webp = ["turbopack-binding/__turbopack_image_webp"]
image-avif = ["turbopack-binding/__turbopack_image_avif"]

# enable "HMR" for embedded assets
dynamic_embed_contents = [
  "turbopack-binding/__turbo_tasks_fs_dynamic_embed_contents",
  "turbopack-binding/__turbopack_dev_dynamic_embed_contents",
]
