[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
semver = "1"
tabled = { version = "0.7", features = ["color"] }
owo-colors = "3"
