[package]
name = "turbo-tasks-build"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
pmutil = "0.5.3"
quote = "1.0"
serde = "1.0.136"
toml = "0.5"
cargo-lock = "7.1.0"

[dependencies.syn]
features = ["full"]
version = "1.0"
