[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"
publish = false

[features]
plugin = ["turbo-binding/__swc_core_binding_napi_plugin"]

[dependencies]
chrono = "0.4"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
hex = "0.4.3"
once_cell = { workspace = true }
next-transform-font = {workspace = true}
pathdiff = "0.2.0"
regex = "1.5"
serde = "1"
serde_json = "1"
sha1 = "0.10.1"
tracing = { version = "0.1.37" }

turbo-binding = { workspace = true, features = [
  "__swc_core",
  "__swc_core_next_core",
  "__swc_transform_styled_jsx",
  "__swc_transform_emotion",
  "__swc_transform_styled_components",
  "__swc_transform_modularize_imports",
  "__swc_transform_relay",
] }

[dev-dependencies]
turbo-binding = { workspace = true, features = [
  "__swc_core_testing_transform",
  "__swc_testing",
] }

walkdir = "2.3.2"
