[package]
name = "turbo-tasks-memory"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[dependencies]
anyhow = { workspace = true }
auto-hash-map = { workspace = true }
concurrent-queue = { workspace = true }
dashmap = { workspace = true }
nohash-hasher = { workspace = true }
num_cpus = "1.13.1"
once_cell = { workspace = true }
parking_lot = { workspace = true }
priority-queue = "1.3.0"
rustc-hash = { workspace = true }
tokio = { workspace = true }
turbo-malloc = { workspace = true, default-features = false }
turbo-tasks = { workspace = true }
turbo-tasks-hash = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
lazy_static = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turbo-tasks-testing = { workspace = true }

[build-dependencies]
turbo-tasks-build = { workspace = true }

[features]
unsafe_once_map = []
log_running_tasks = []
log_scheduled_tasks = []
log_activate_tasks = []
log_connect_tasks = []
report_expensive = []
print_scope_updates = []
print_task_invalidation = []
inline_add_to_scope = []
inline_remove_from_scope = []

[[bench]]
name = "mod"
harness = false
