on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/next/build/swc/**'

name: Build next-swc native binaries

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]

    name: stable - ${{ matrix.os }} - node@14
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: stable-${{ matrix.os }}-node@14-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: stable-${{ matrix.os }}-node@14-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-cache-${{ matrix.os }}-node@14-${{ hashFiles('yarn.lock') }}

      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: 'Build'
        run: yarn --cwd packages/next build-native
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.13'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-swc-binaries
          path: packages/next/native

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache

  build-apple-silicon:
    name: stable - aarch64-apple-darwin - node@14
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Install dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Cross build aarch64
        run: yarn --cwd packages/next build-native --target aarch64-apple-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-swc-binaries
          path: packages/next/native

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache

  commit:
    needs: [build, build-apple-silicon]
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        if: ${{ env.GITHUB_EVENT_NAME  == 'workflow_dispatch' }}
      - uses: actions/download-artifact@v2
        with:
          name: next-swc-binaries
          path: packages/next/native
        if: ${{ env.GITHUB_EVENT_NAME  == 'workflow_dispatch' }}
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'packages/next/native --force'
          message: 'Build next-swc binaries'
        if: ${{ env.GITHUB_EVENT_NAME  == 'workflow_dispatch' }}

  check:
    needs: [build, build-apple-silicon]
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}
      - uses: actions/download-artifact@v2
        with:
          name: next-swc-binaries
          path: packages/next/native
        if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}
      - run: git diff --exit-code
        if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}

  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Install
        if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          profile: minimal
      - run: cd packages/next/build/swc && cargo test
        if: ${{ env.GITHUB_EVENT_NAME  == 'pull_request' }}
