name: On issue comment

on:
  issue_comment:
    types: [created]

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/needs-triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  minus-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Manage +1 comments'
        run: node ./.github/actions/minus-one
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
