name: Notify about approved but still open PRs

on:
  schedule:
    - cron: '0 0 * * *' # Once a day
  workflow_dispatch:

jobs:
  pr-approved-open:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - name: 'Send notification to Slack'
        run: node ./.github/actions/pr-approved-open/index.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
