on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0,12 * * *'

name: Test react@experimental

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn install --frozen-lockfile --check-files
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - run: yarn upgrade react@experimental react-dom@experimental -W --dev

      - run: node run-tests.js --timings --write-timings -g 1/1

      - uses: actions/cache@v3
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-react-experimental

  testAll:
    name: Test All
    runs-on: ubuntu-latest
    needs: build
    env:
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PRIVATE_REACT_ROOT: 1
      NEXT_PRIVATE_SKIP_SIZE_TESTS: true
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-react-experimental

      - run: npm i -g pnpm@latest

      - run: npm i -g playwright-chromium@1.22.2 && npx playwright install-deps

      - run: node run-tests.js --timings -g ${{ matrix.group }}/6
