name: Test E2E (Vercel Deploy), scheduled

on:
  schedule:
    # run every day at midnight
    - cron: '0 0 * * *'
  # allow triggering manually as well
  workflow_dispatch:

jobs:
  test:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest

    env:
      CARGO_PROFILE_RELEASE_LTO: 'true'
      DATADOG_API_KEY: ${{ secrets.DATA_DOG_API_KEY }}
      DD_ENV: 'ci'
      NAPI_CLI_VERSION: 2.16.2
      NEXT_JUNIT_TEST_REPORT: 'true'
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_TEST_CONTINUE_ON_ERROR: 1
      NEXT_TEST_JOB: 1
      NEXT_TEST_MODE: 'deploy'
      NODE_LTS_VERSION: 20
      TEST_TIMINGS_TOKEN: ${{ secrets.TEST_TIMINGS_TOKEN }}
      TURBO_REMOTE_ONLY: 'true'
      TURBO_TEAM: 'vercel'
      TURBO_VERSION: 1.12.5
      VERCEL_TEST_TEAM: vtest314-next-e2e-tests
      VERCEL_TEST_TOKEN: ${{ secrets.VERCEL_TEST_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 25

      - name: Setup tests
        run: |
          pnpm setup
          pnpm install
          pnpx playwright install --with-deps
          pnpm run build
          pnpm i -g vercel@latest
          node scripts/run-e2e-test-project-reset.mjs

      - name: Run tests
        run: xvfb-run node run-tests.js --related

      - name: Save test report as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          if-no-files-found: ignore
          retention-days: 2
          path: test/test-junit-report

      - name: Upload test report to Datadog
        continue-on-error: true
        run: |
          pnpx @datadog/datadog-ci@2.23.1 junit upload --tags test.type:nextjs_deploy_e2e --service nextjs ./test/test-junit-report
