name: Turbopack Next.js development integration tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  test-dev:
    name: Next.js integration tests
    uses: ./.github/workflows/integration_tests_reusable.yml
    with:
      name: turbopack-development
      test_type: development
      run_before_test: |
        export TURBOPACK=1
      datadog_args: --tags test.type:turbopack.daily --service Turbopack
    secrets: inherit
